export function createSeedData(hashPassword) {
  const now = "2026-04-27T08:30:00.000Z";

  return {
    users: [
      {
        id: "user-admin",
        name: "Maya Singh",
        email: "admin@relief.org",
        role: "admin",
        organization: "ReliefSync Demo NGO",
        passwordHash: hashPassword("demo1234"),
        createdAt: now,
      },
      {
        id: "user-ngo",
        name: "Aarav Mehta",
        email: "ngo@relief.org",
        role: "ngo",
        organization: "ReliefSync Demo NGO",
        passwordHash: hashPassword("demo1234"),
        createdAt: now,
      },
      {
        id: "user-volunteer",
        name: "Alex Johnson",
        email: "volunteer@email.com",
        role: "volunteer",
        volunteerId: "vol-1",
        passwordHash: hashPassword("demo1234"),
        createdAt: now,
      },
      {
        id: "user-volunteer-2",
        name: "Dr. Emily Roberts",
        email: "emily@relief.org",
        role: "volunteer",
        volunteerId: "vol-2",
        passwordHash: hashPassword("demo1234"),
        createdAt: now,
      },
    ],
    volunteers: [
      {
        id: "vol-1",
        userId: "user-volunteer",
        name: "Alex Johnson",
        email: "volunteer@email.com",
        phone: "+1 555 0142",
        location: "District 5",
        skills: ["Medical", "Transport", "Communication", "Emergency Response"],
        categories: ["Medical", "Transport", "Food"],
        availability: "available",
        availableDays: ["Monday", "Tuesday", "Wednesday", "Saturday"],
        capacity: 4,
        workload: 1,
        completedTasks: 42,
        hoursVolunteered: 156,
        rating: 4.9,
        pastAssignments: ["Medical", "Food", "Transport"],
        joinedDate: "January 2025",
        bio: "Reliable field volunteer with vehicle access and basic medical training.",
      },
      {
        id: "vol-2",
        userId: "user-volunteer-2",
        name: "Dr. Emily Roberts",
        email: "emily@relief.org",
        phone: "+1 555 0151",
        location: "District 5",
        skills: ["Medical", "First Aid", "Emergency Response", "Triage"],
        categories: ["Medical", "Shelter"],
        availability: "available",
        availableDays: ["Monday", "Tuesday", "Thursday"],
        capacity: 3,
        workload: 0,
        completedTasks: 47,
        hoursVolunteered: 210,
        rating: 4.9,
        pastAssignments: ["Medical", "Shelter"],
        joinedDate: "March 2024",
        bio: "Physician supporting urgent triage and community health drives.",
      },
      {
        id: "vol-3",
        name: "James Wilson",
        email: "james@relief.org",
        phone: "+1 555 0160",
        location: "District 2",
        skills: ["Food", "Logistics", "Communication", "Inventory"],
        categories: ["Food", "Transport"],
        availability: "available",
        availableDays: ["Tuesday", "Friday", "Sunday"],
        capacity: 5,
        workload: 2,
        completedTasks: 38,
        hoursVolunteered: 120,
        rating: 4.8,
        pastAssignments: ["Food", "Transport"],
        joinedDate: "June 2024",
        bio: "Food distribution lead with logistics experience.",
      },
      {
        id: "vol-4",
        name: "Sarah Martinez",
        email: "sarah@relief.org",
        phone: "+1 555 0167",
        location: "District 7",
        skills: ["Shelter", "Community Outreach", "Childcare", "Documentation"],
        categories: ["Shelter", "Clothing", "Counseling"],
        availability: "limited",
        availableDays: ["Wednesday", "Saturday"],
        capacity: 2,
        workload: 1,
        completedTasks: 52,
        hoursVolunteered: 188,
        rating: 5,
        pastAssignments: ["Shelter", "Clothing"],
        joinedDate: "September 2023",
        bio: "Community organizer focused on displaced families and safe shelter intake.",
      },
      {
        id: "vol-5",
        name: "Michael Chen",
        email: "michael@relief.org",
        phone: "+1 555 0188",
        location: "District 4",
        skills: ["Transport", "Warehouse", "Heavy Lifting", "Inventory"],
        categories: ["Transport", "Clothing", "Food"],
        availability: "busy",
        availableDays: ["Sunday"],
        capacity: 3,
        workload: 3,
        completedTasks: 29,
        hoursVolunteered: 96,
        rating: 4.7,
        pastAssignments: ["Transport", "Clothing"],
        joinedDate: "May 2025",
        bio: "Warehouse and delivery volunteer with weekend availability.",
      },
    ],
    needs: [
      {
        id: "need-1",
        rawText:
          "Urgent: District 5 community center is running out of first aid kits, bandages, insulin support, and basic medication for 50+ families with children and elderly residents.",
        title: "Emergency Medical Supplies",
        category: "Medical",
        urgency: "critical",
        priorityScore: 92,
        summary:
          "District 5 needs immediate first aid kits, bandages, insulin support, and medication for 50+ families including children and elderly residents.",
        reason:
          "Heuristic priority: Medical category severity, multiple urgency clues, vulnerable group clues, resource scarcity wording, 50 people affected.",
        keywords: ["urgent", "district", "medical", "first", "aid", "insulin", "children", "elderly"],
        location: "District 5, Community Center",
        reporter: "Sarah Johnson",
        affectedPeople: 50,
        status: "pending",
        createdAt: "2026-04-27T06:45:00.000Z",
        updatedAt: "2026-04-27T06:45:00.000Z",
        aiSource: "fallback",
      },
      {
        id: "need-2",
        rawText:
          "Food pantry at Main Street Shelter in District 2 is low. Need rice, canned food, baby formula, and volunteers for weekly distribution to 80 people by tomorrow morning.",
        title: "Food Distribution Support",
        category: "Food",
        urgency: "high",
        priorityScore: 76,
        summary:
          "District 2 shelter needs food supplies and distribution support for 80 people by tomorrow morning.",
        reason:
          "Heuristic priority: Food category severity, time-sensitive wording, resource scarcity wording, 80 people affected.",
        keywords: ["food", "district", "shelter", "rice", "canned", "formula", "distribution", "tomorrow"],
        location: "District 2, Main Street Shelter",
        reporter: "Michael Chen",
        affectedPeople: 80,
        status: "assigned",
        assignedVolunteerId: "vol-1",
        createdAt: "2026-04-26T12:10:00.000Z",
        updatedAt: "2026-04-27T07:30:00.000Z",
        aiSource: "fallback",
      },
      {
        id: "need-3",
        rawText:
          "Family of five displaced by apartment fire in District 7 needs temporary shelter, blankets, and childcare support tonight.",
        title: "Temporary Shelter Needed",
        category: "Shelter",
        urgency: "high",
        priorityScore: 73,
        summary:
          "A family displaced by a fire in District 7 needs temporary shelter, blankets, and childcare support tonight.",
        reason:
          "Heuristic priority: Shelter category severity, time-sensitive wording, vulnerable family indicator.",
        keywords: ["family", "displaced", "fire", "district", "shelter", "blankets", "childcare", "tonight"],
        location: "District 7, North Zone",
        reporter: "Emma Williams",
        affectedPeople: 5,
        status: "pending",
        createdAt: "2026-04-25T15:20:00.000Z",
        updatedAt: "2026-04-25T15:20:00.000Z",
        aiSource: "fallback",
      },
      {
        id: "need-4",
        rawText:
          "Lincoln Elementary requests books, stationery, and learning material kits for 120 students from low-income families this month.",
        title: "Educational Supplies For School",
        category: "Education",
        urgency: "medium",
        priorityScore: 42,
        summary:
          "Lincoln Elementary needs learning materials and stationery for 120 students from low-income families.",
        reason: "Heuristic priority: Education category severity and 120 people affected.",
        keywords: ["lincoln", "elementary", "books", "stationery", "students", "families"],
        location: "District 3, Lincoln Elementary",
        reporter: "David Martinez",
        affectedPeople: 120,
        status: "completed",
        assignedVolunteerId: "vol-4",
        createdAt: "2026-04-21T10:00:00.000Z",
        updatedAt: "2026-04-24T16:00:00.000Z",
        aiSource: "fallback",
      },
    ],
    assignments: [
      {
        id: "asgn-1",
        needId: "need-2",
        volunteerId: "vol-1",
        status: "pending_acceptance",
        assignedAt: "2026-04-27T07:30:00.000Z",
        updatedAt: "2026-04-27T07:30:00.000Z",
        assignedBy: "user-admin",
      },
      {
        id: "asgn-2",
        needId: "need-4",
        volunteerId: "vol-4",
        status: "completed",
        assignedAt: "2026-04-22T08:30:00.000Z",
        updatedAt: "2026-04-24T16:00:00.000Z",
        assignedBy: "user-ngo",
      },
    ],
    sessions: [],
  };
}
